
namespace LibgenApi.LI.OptionTypes.FieldsEnums
{
    public enum EditionFields
    {
        title,
        libgen_topic,
        type,
        series_name,
        title_add,
        author,
        publisher,
        city,
        edition,
        year,
        month,
        day,
        pages,
        editions_add_info,
        cover_url,
        issue_s_id,
        issue_number_in_year,
        issue_year_number,
        issue_number,
        issue_volume,
        issue_split,
        issue_total_number,
        issue_first_page,
        issue_last_page,
        issue_year_end,
        issue_month_end,
        issue_day_end,
        issue_closed,
        doi,
        time_added,
        time_last_modified,
        visible,
        editable,
        commentary,
        cover_exists
    }
}
