
namespace LibgenApi.LI.OptionTypes.AddKeysEnums
{
    public enum EditionAddKeys
    {
        mainTitleOriginal = 10,
        mainTitleEngTranslate = 13,
        containerTitle = 20,
        lang = 101,
        langOriginal = 102,
        site = 306,
        publisherId = 308, //optional attribute: Name Variant
        linksOther = 309,
        author = 401, //optional attribute: Role, Library, LibraryID
        authorID = 402, //optional attribute: Role, Variant (Pseudonim)
        isbn = 505, //optional attribute: ISBN notes
        issn = 501, //optional attribute: Type
        udc = 602,
        ddc = 603,
        topicComics = 604,
        topicBooks = 606,
        standartType = 607, //optional attribute: Standart Number, Standart Date
        standartNum = 608,
        parentDoc = 609,
        series = 630, //optional attribute: Number, Library, LibraryID
        seriesID = 631, //optional attribute: #, Name variant
        replacedInPart = 632,
        relatedTo = 633,
        relatedIn = 634,
        replacedTo = 635,
        replacedToPart = 636,
        replacedIn = 637,
        publishingInfo = 638,
        lbc = 639,
        standartStatus = 750, //optional attribute: Additional Standart status
        awards = 770, //optional attribute: Year
        datePublication = 820,
        dateIntroduction = 821,
        dateActualText = 822,
        dateRegistr = 823,
        dateActualDescr = 824,
        dateExpire = 825,
        dateLastEdit = 826,
        coverUrl = 863, //optional attribute: Cover Name, Creator(s), Sidebar Location
        pii = 902,
        pmcID = 903,
        pmID = 904,
        asin = 908,
        bl = 909,
        bnb = 910,
        bnf = 911,
        copac = 912,
        dnb = 913,
        fantLabEditionID = 914,
        goodreads = 915,
        jnb_jpno = 916,
        lccn = 917,
        ndl = 918,
        oclc_worldCat = 919,
        openLib = 920,
        sfbg = 921,
        bn = 922,
        ppn = 923,
        audibleASIN = 924,
        ltf = 925,
        kbr = 926,
        reginald1 = 927,
        reginald3 = 928,
        bleilerGernsback = 929,
        bleilerSupernatural = 930,
        bleilerEarlyYears = 931,
        nilf = 932,
        nooSFere = 933,
        SFLeihbuch = 934,
        nla = 935,
        porbase = 936,
        isfdbTitleID = 943,
        googleID = 945,
        jstorStableID = 946,
        crossrefID = 947,
        classification = 950,
        classificationOKP = 951,
        classificationGOST = 952,
        classificationOKS = 953,
        classificationLibCongress = 954,
        tags = 990,
        tableOfContents = 995,
        description = 996,
        notes = 999
    }
}
